[project]
name = "simpleplot"
version = "0.1.0"
description = "Create plots in a straigh-forward manner"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pyqt6>=6.9.1",
    "pytest>=8.3.5",
]
